### ISSUE TITLE
Login pixiv failed (correct password)

### ISSUE THREAD

**Issue by AlZarych** [catgirlfighter/nekopaw#352]
Авторизация не проходит. Пишет 
17:47:46 pixiv.net error: http://pixiv.net/login.php: Connect timed out.
17:47:46 pixiv.net: login is failed
17:47:46 pixiv.net: @thread.execute(): http://pixiv.net/login.php: Connect timed out.

**Comment by HanatakeYurii** [comment]
Almost the same here:
23:50:23 pixiv.net error: http://pixiv.net/login.php: HTTP/1.1 400 Bad Request
23:50:23 pixiv.net: login is failed
23:50:23 pixiv.net: @thread.execute(): http://pixiv.net/login.php: HTTP/1.1 400 Bad Request

**Comment by tombmonkey** [comment]
Yeah they changed something again.
07:11:44 pixiv.net error: http://pixiv.net/login.php: HTTP/1.1 400 Bad Request
07:11:44 pixiv.net: login is failed
07:11:44 pixiv.net: @thread.execute(): http://pixiv.net/login.php: HTTP/1.1 400 Bad Request

**Comment by Ruriko** [comment]
Hmm no updates for a few weeks now I wonder if admin is gone?

**Comment by WhiteSp1rit** [comment]
In light of no foreseeable fix, can someone recommend another similar program for downloading from Pixiv and other sources?

**Comment by EtherealPanda** [comment]
Since development is dead, I found PixivUtil2 to be better for downloading from pixiv... and frequently updated by the author. 

Nekopaw has very few options and frequently misses about 6 or 8 pics when grabbing whole gallery's, including gifs.

@WhiteSp1rit https://github.com/Nandaka/PixivUtil2/releases

**Comment by JarieSuicune** [comment]
So... how do you even use PixivUtil2? I try to run it, a Command window pops for a half second, then closes. Nada.
Does it have a UI, and how do I find it?

**Comment by EtherealPanda** [comment]
@JarieSuicune  It uses command as it's UI. Try running windows cmd first as admin and drag exe into command window.

**Comment by catgirlfighter** [comment]
Fixed it for "standard" version. Don't know if it fixed for you.
There also was "whitecube" version, but for some reason I can't access it from my "alternative nation" account anymore, so I couldn't check.

Also fixed the animation packs. Not sure, what panda meant by "gifs" that couldn't be downloaded.

**Comment by JarieSuicune** [comment]
>_< Thank you! Welcome back, I hope you are doing well!

**Comment by EtherealPanda** [comment]
My apologies for my first comment, it's been awhile since the last update so i thought you stopped working on the program. Glad to see it's fixed. 

I meant that i still get errors when grabbing galleries that have animations.
![screen shot 02-19-17 at 07 53 pm](https://cloud.githubusercontent.com/assets/25573302/23113599/05cbb812-f6ee-11e6-99db-79961fae85ac.PNG)

21:23:58 .%ext%: HTTP/1.1 400 Bad Request
21:24:02 .%ext%: HTTP/1.1 400 Bad Request
21:24:06 .%ext%: HTTP/1.1 400 Bad Request

If possible there should be an option to convert animation packs automatically to webm/gif.

**Comment by catgirlfighter** [comment]
I'll look into it.
Conversion to gif isn't an option, it's not actual animated pictures, but series of normal pictures, just shown one after another by a script (zip archive you get that's what it's actually are), so converting it into gif will follow with serious quality loss. But I'll check, what I can do to convert it to webm.

**Comment by catgirlfighter** [comment]
You didn't provide me neither tag nor source (normal search, works, favorites?), so I looked into int by intuition. My previous fix worked only on normal search, but not works and favorites. And I was getting different from you error messages, too. I fixed it, but I'm not sure if it was the same errors you were getting.

I found one resource that does easy conversion from zip-pack to webm
http://ugoira.dataprocessingclub.org/
but it doesn't do it on demand ( you have to wait for unknown amount of time waiting for counter-request from server), and it's inconsistent (it may be down whenever it wants), so I didn't use it.

Nekopaw will never wait for requests, and if I would want to make it myself, I would need some quite specific knowledge about ffmpeg library (I really don't want to use 3rd party exe files nor applications as middlemen). It may require some effort from me, so I don't promise anything :)

**Comment by tombmonkey** [comment]
Dude leave the whole animation -> webm thing out, it falls outside the scope of the grabber, if people want to turn them to animation again let them make a gif or video on their own.

Thanks for fixing the pixiv login issue.

**Comment by catgirlfighter** [comment]
I can add something to make it easier, like "execute command string when downloaded", or something like that. I don't like an idea of leaving a batch of animation parts "unfinished", too.
But, I guess, I'll keep doing it outside of current issue.
